Repository prgrms-web-devcourse-final-project/WEB2_3_CUBE_BE, pull requests merged in 2025-03, with the labels that each got.

#210 Feat/#209 read cd comments all
  roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java
  roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java
  roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
  roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java
  roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
Labels: enhancement

#213 Refactor: CD 댓글 삭제 권한 로직 수정 및 타임스탬프 필드 변경
  roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java
  roome/src/main/java/com/roome/domain/cdcomment/controller/MockCdCommentController.java
  roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentCreateRequest.java
  roome/src/main/java/com/roome/domain/cdcomment/dto/CdCommentResponse.java
  roome/src/main/java/com/roome/domain/cdcomment/entity/CdComment.java
  roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
  roome/src/main/java/com/roome/global/exception/ForbiddenException.java
  roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java
  roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
Labels: enhancement

#230 feat: CD 목록 조회 시 로그인한 사용자와 조회 대상 사용자 구분 가능하도록 수정
  roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
Labels: enhancement

#238 Feat: 특정 CD 조회 시 targetUserId 적용 기능 추가
  roome/src/main/java/com/roome/domain/mycd/controller/MyCdController.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
Labels: enhancement

#243 Feat: 회원 탈퇴 로직 개선 및 Redis 재시도 적용
  roome/build.gradle
  roome/src/main/java/com/roome/RoomeApplication.java
  roome/src/main/java/com/roome/domain/auth/controller/AuthController.java
  roome/src/main/java/com/roome/domain/auth/service/CustomOAuth2UserService.java
  roome/src/main/java/com/roome/domain/guestbook/repository/GuestbookRepository.java
  roome/src/main/java/com/roome/domain/houseMate/repository/HousemateRepository.java
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/repository/PointRepository.java
  roome/src/main/java/com/roome/domain/room/entity/Room.java
  roome/src/main/java/com/roome/domain/user/entity/User.java
  roome/src/main/java/com/roome/domain/user/service/UserService.java
  roome/src/main/java/com/roome/global/jwt/controller/ReissueController.java
  roome/src/main/java/com/roome/global/service/RedisService.java
  roome/src/test/java/com/roome/domain/auth/controller/AuthControllerTest.java
  roome/src/test/java/com/roome/domain/auth/controller/WithdrawControllerTest.java
  roome/src/test/java/com/roome/domain/user/service/UserServiceTest.java
  roome/src/test/java/com/roome/global/service/RedisServiceTest.java
Labels: enhancement

#245 Refactor: CD 삭제 시 권한 검증 추가 및 조회/검색/중복 체크 최적화
  roome/src/main/java/com/roome/domain/mycd/controller/MockMyCdController.java
  roome/src/main/java/com/roome/domain/mycd/dto/MyCdListResponse.java
  roome/src/main/java/com/roome/domain/mycd/exception/MyCdUnauthorizedException.java
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
  roome/src/main/java/com/roome/global/exception/ErrorCode.java
Labels: enhancement

#247 Refactor: CD 목록 조회 API의 totalCount, firstMyCdId, lastMyCdId 개선
  roome/src/main/java/com/roome/domain/mycd/exception/MyCdDatabaseException.java
  roome/src/main/java/com/roome/domain/mycd/exception/MyCdPaginationException.java
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
Labels: refactor

#260 Feat: 포인트 적립/차감/조회 및 포인트 내역 조회 기능 추가
  roome/src/main/java/com/roome/domain/guestbook/service/GuestbookService.java
  roome/src/main/java/com/roome/domain/point/controller/PointController.java
  roome/src/main/java/com/roome/domain/point/dto/PointBalanceResponse.java
  roome/src/main/java/com/roome/domain/point/dto/PointHistoryDto.java
  roome/src/main/java/com/roome/domain/point/dto/PointHistoryResponse.java
  roome/src/main/java/com/roome/domain/point/entity/PointHistory.java
  roome/src/main/java/com/roome/domain/point/entity/PointReason.java
  roome/src/main/java/com/roome/domain/point/exception/DuplicatePointEarnException.java
  roome/src/main/java/com/roome/domain/point/exception/InvalidPointOperationException.java
  roome/src/main/java/com/roome/domain/point/exception/PointHistoryEmptyException.java
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
  roome/src/main/java/com/roome/domain/user/entity/User.java
  roome/src/main/java/com/roome/global/exception/ErrorCode.java
  roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceEventTest.java
  roome/src/test/java/com/roome/domain/guestbook/service/GuestbookServiceTest.java
  roome/src/test/java/com/roome/domain/mycd/controller/MyCdControllerTest.java
  roome/src/test/java/com/roome/domain/notification/listener/NotificationEventListenerTest.java
  roome/src/test/java/com/roome/domain/point/service/PointServiceTest.java
  roome/src/test/java/com/roome/global/notificationEvent/NotificationEventTest.java
Labels: enhancement

#273 Feat: 선착순 이벤트 참여 기능 구현
  roome/src/main/java/com/roome/RoomeApplication.java
  roome/src/main/java/com/roome/domain/event/controller/FirstComeEventController.java
  roome/src/main/java/com/roome/domain/event/entity/EventParticipation.java
  roome/src/main/java/com/roome/domain/event/entity/FirstComeEvent.java
  roome/src/main/java/com/roome/domain/event/exception/AlreadyParticipatedException.java
  roome/src/main/java/com/roome/domain/event/exception/EventFullException.java
  roome/src/main/java/com/roome/domain/event/exception/EventNotFoundException.java
  roome/src/main/java/com/roome/domain/event/exception/EventNotStartedException.java
  roome/src/main/java/com/roome/domain/event/repository/EventParticipationRepository.java
  roome/src/main/java/com/roome/domain/event/repository/FirstComeEventRepository.java
  roome/src/main/java/com/roome/domain/event/service/FirstComeEventScheduler.java
  roome/src/main/java/com/roome/domain/event/service/FirstComeEventService.java
  roome/src/main/java/com/roome/domain/point/exception/PointNotFoundException.java
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
  roome/src/main/java/com/roome/global/exception/ErrorCode.java
Labels: enhancement

#279 Refactor: 주간 랭킹 보상 시스템 개선
  roome/src/main/java/com/roome/domain/point/entity/PointReason.java
  roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java
  roome/src/test/java/com/roome/domain/rank/service/RankingSchedulerTest.java
Labels: refactor

#282 Refactor: 포인트 도메인 예외 처리/코드 정리
  roome/src/main/java/com/roome/domain/payment/service/PaymentService.java
  roome/src/main/java/com/roome/domain/point/controller/PointController.java
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/repository/PointRepository.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
  roome/src/main/java/com/roome/domain/rank/service/RankingScheduler.java
Labels: enhancement

#291 Feat: 선착순 이벤트 상태 관리 방식 개선 및 조회 기능 추가
  roome/src/main/java/com/roome/domain/event/controller/FirstComeEventController.java
  roome/src/main/java/com/roome/domain/event/dto/FirstComeEventResponse.java
  roome/src/main/java/com/roome/domain/event/entity/EventStatus.java
  roome/src/main/java/com/roome/domain/event/entity/FirstComeEvent.java
  roome/src/main/java/com/roome/domain/event/repository/FirstComeEventRepository.java
  roome/src/main/java/com/roome/domain/event/service/FirstComeEventScheduler.java
  roome/src/main/java/com/roome/domain/event/service/FirstComeEventService.java
Labels: enhancement

#293 Test: CdCommentController & CdCommentService 테스트 커버리지 개선
  roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
  roome/src/test/java/com/roome/domain/cdcomment/controller/CdCommentControllerTest.java
  roome/src/test/java/com/roome/domain/cdcomment/service/CdCommentServiceTest.java
Labels: enhancement

#307 Fix: 포인트 내역 조회 시 firstId, lastId를 전체 기준으로 변경
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
Labels: bug

#340 Feat: QueryDSL 기반 검색 기능 추가 및 성능 최적화
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdQueryRepository.java
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdQueryRepositoryImpl.java
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
  roome/src/test/java/com/roome/domain/mycd/controller/MyCdControllerTest.java
  roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
Labels: enhancement

#342 Feat: Redis 캐싱 적용 및 MyCd 조회 성능 개선
  roome/build.gradle
  roome/src/main/java/com/roome/domain/mycd/dto/MyCdListResponse.java
  roome/src/main/java/com/roome/domain/mycd/dto/MyCdResponse.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
  roome/src/main/java/com/roome/global/config/RedisConfig.java
Labels: enhancement

#348 Feat: CD 단건 조회 API 부하테스트 및 최적화
  roome/src/main/java/com/roome/domain/mycd/repository/MyCdRepository.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
  roome/src/main/java/com/roome/global/config/RedisConfig.java
  roome/src/test/java/com/roome/domain/mycd/service/MyCdServiceTest.java
Labels: enhancement

#358 Refactor: Spring 트랜잭션 적용 및 CD 댓글 조회 로직 최적화
  roome/src/main/java/com/roome/domain/cdcomment/controller/CdCommentController.java
  roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java
  roome/src/main/java/com/roome/domain/cdcomment/service/CdCommentService.java
Labels: enhancement

#360 Fix: ForbiddenException 발생 시 500 → 403으로 반환되도록 예외 처리 추가
  roome/src/main/java/com/roome/global/exception/GlobalExceptionHandler.java
Labels: bug

#367 Feat: CdTemplate 중복 체크 후 저장 로직 추가
  roome/src/main/java/com/roome/domain/cdtemplate/exception/DuplicateCdTemplateException.java
  roome/src/main/java/com/roome/domain/cdtemplate/repository/CdTemplateRepository.java
  roome/src/main/java/com/roome/domain/cdtemplate/service/CdTemplateService.java
  roome/src/test/java/com/roome/domain/mybookreview/controller/MyBookReviewControllerTest.java
Labels: enhancement

#369 Feat: 포인트 시스템 동시성 처리
  roome/build.gradle
  roome/src/main/java/com/roome/domain/point/controller/PointController.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
  roome/src/main/java/com/roome/global/config/RedissonConfig.java
  roome/src/main/java/com/roome/global/config/SecurityConfig.java
  roome/src/main/java/com/roome/global/exception/LockAcquisitionFailedException.java
  roome/src/main/java/com/roome/global/service/RedisLockService.java
Labels: enhancement

#380 Fix: MyCd 삭제 시 MyCdCount 개수 감소 로직 추가
  roome/src/main/java/com/roome/domain/cdcomment/repository/CdCommentRepository.java
  roome/src/main/java/com/roome/domain/houseMate/listener/UserStatusEventListener.java
  roome/src/main/java/com/roome/domain/mycd/service/MyCdService.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
  roome/src/main/java/com/roome/domain/rank/controller/RankingController.java
  roome/src/main/java/com/roome/domain/rank/service/RankingService.java
  roome/src/main/java/com/roome/domain/user/service/UserService.java
  roome/src/main/java/com/roome/global/config/AsyncConfig.java
  roome/src/main/java/com/roome/global/config/RedissonConfig.java
Labels: enhancement

#387 Feat: 포인트 내역 조회 커서 기반 페이징 개선
  roome/src/main/java/com/roome/domain/point/controller/PointController.java
  roome/src/main/java/com/roome/domain/point/dto/PointHistoryGroupedDto.java
  roome/src/main/java/com/roome/domain/point/dto/PointHistoryResponse.java
  roome/src/main/java/com/roome/domain/point/repository/PointHistoryRepository.java
  roome/src/main/java/com/roome/domain/point/service/PointService.java
Labels: enhancement

#392 Feat: cd_template 테이블에 user_id 컬럼 추가 및 저장 로직 수정
  roome/src/main/java/com/roome/domain/cdtemplate/entity/CdTemplate.java
  roome/src/main/java/com/roome/domain/cdtemplate/repository/CdTemplateRepository.java
  roome/src/main/java/com/roome/domain/cdtemplate/service/CdTemplateService.java
Labels: enhancement
